export const FETCH_ROOMS_REQUEST = "FETCH_ROOMS_REQUEST";
export const FETCH_ROOMS_SUCCESS = "FETCH_ROOMS_SUCCESS";
export const FETCH_ROOMS_FAILURE = "FETCH_ROOMS_FAILURE";
export const UPDATE_ROOM_USERS = "UPDATE_ROOM_USERS";

export const RESET_USER_STATE = "RESET_USER_STATE";
export const SET_USER_STATE = "SET_USER_STATE";
export const SET_USER_MASTER = "SET_USER_MASTER";

export const SET_USER_GAME_START = "SET_USER_GAME_START";
export const USER_DRAW_TURN = "USER_DRAW_TURN";
export const USER_DRAW_START = "USER_DRAW_START";
export const USER_SET_WORDS = "USER_SET_WORDS";
export const GAME_FINISH = "GAME_FINISH";
export const RESET_SCORE = "RESET_SCORE";

export const ADD_NEW_MESSAGE = "ADD_NEW_MESSAGE";
export const RESET_USER_CHAT = "RESET_USER_CHAT";

export const SOCKET_CONNECTED = "SOCKET_CONNECTED";