export const FETCH_ROOMS_REQUEST = "FETCH_ROOMS_REQUEST";
export const FETCH_ROOMS_SUCCESS = "FETCH_ROOMS_SUCCESS";
export const FETCH_ROOMS_FAILURE = "FETCH_ROOMS_FAILURE";
export const UPDATE_ROOM_USERS = "UPDATE_ROOM_USERS";

export const SET_USER_STATE = "SET_USER_STATE";
export const SET_USER_MASTER = "SET_USER_MASTER";

export const ADD_NEW_MESSAGE = "ADD_NEW_MESSAGE";

export const SOCKET_CONNECTED = "SOCKET_CONNECTED";